//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allergens()
        {
            this.FoodAllergenPairs = new HashSet<FoodAllergenPairs>();
        }
    
        public int AllergenID { get; set; }
        public string AllergenName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodAllergenPairs> FoodAllergenPairs { get; set; }
    }
}
