//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodAllergenPairs
    {
        public int PairID { get; set; }
        public int AllergenID { get; set; }
        public int FoodID { get; set; }
    
        public virtual Allergens Allergens { get; set; }
        public virtual Foods Foods { get; set; }
    }
}
