//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foods()
        {
            this.FoodAllergenPairs = new HashSet<FoodAllergenPairs>();
            this.FoodOfaDay = new HashSet<FoodOfaDay>();
        }
    
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public int TypeID { get; set; }
        public string Recepy { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodAllergenPairs> FoodAllergenPairs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodOfaDay> FoodOfaDay { get; set; }
        public virtual FoodTypes FoodTypes { get; set; }
    }
}
