//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodApplicationDBEntities : DbContext
    {
        public FoodApplicationDBEntities()
            : base("name=FoodApplicationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergens> Allergens { get; set; }
        public virtual DbSet<FavouriteMenus> FavouriteMenus { get; set; }
        public virtual DbSet<FoodAllergenPairs> FoodAllergenPairs { get; set; }
        public virtual DbSet<FoodOfaDay> FoodOfaDay { get; set; }
        public virtual DbSet<Foods> Foods { get; set; }
        public virtual DbSet<FoodTypes> FoodTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeekMenus> WeekMenus { get; set; }
    }
}
